# Generated by Django 4.0.4 on 2024-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=25)),
                ('items', models.JSONField()),
                ('lat_long', models.CharField(max_length=60)),
                ('full_details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
