# Generated by Django 4.0.4 on 2024-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='Restaurant',
        ),
    ]
